overwrite: true
schema: "http://localhost:4000/graphql"
documents: "src/lib/graphql/**/*.graphql"
watch: true
generates:
  src/lib/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
      - "fragment-matcher"
