overwrite: true
schema: "../server/schema.gql"
documents: "src/lib/graphql/**/*.graphql"
watch: true
generates:
  src/lib/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
      - "fragment-matcher"
